JDX-18.4
JanSikorski/TaskApp pull request #3
Opened 2023-01-29 21:24 UTC by JanSikorski

2023-01-30 16:52 UTC, mps4dev requested changes

2023-01-30 16:52 UTC, mps4dev commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +    @GetMapping
Tu czegos brakuje chyba

2023-02-01 16:55 UTC, mps4dev requested changes

2023-02-01 16:55 UTC, mps4dev commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +    @GetMapping(value = "taskId")
"{taskId}"

/v1/tasks/6.  => taskId = 6

return new TaskDto(taskId, "test title", "test_content");

2023-02-01 16:55 UTC, mps4dev commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +    @DeleteMapping
j.w.

2023-02-02 15:38 UTC, mps4dev requested changes
No przeciez mowilem, jak ma byc

2023-02-02 21:46 UTC, JanSikorski commented
Powprawiłem z "taskId" na "{taskId}"

2023-02-03 15:26 UTC, mps4dev approved these changes

2023-02-04 00:14 UTC, closed without merging