JDX-19.2
JanSikorski/TaskApp pull request #5
Opened 2023-01-31 21:42 UTC by JanSikorski

2023-02-01 16:51 UTC, mps4dev requested changes

2023-02-01 16:51 UTC, mps4dev commented on src/main/java/com/crud/tasks/mapper/TaskMapper.java
> +    public TaskDto mapToTaskDto(final Optional<Task> task) {
Parametry metod nie sa Optionalem

2023-02-01 16:51 UTC, mps4dev commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +        Optional<Task> task = service.findById(taskId);
Task task = service.findById(taskId).orElse(null);

2023-02-01 16:51 UTC, mps4dev commented on src/main/java/com/crud/tasks/mapper/TaskMapper.java
> +    public TaskDto mapToTaskDto(final Optional<Task> task) {
if (task == null) {
return null;
}

2023-02-02 15:39 UTC, mps4dev requested changes

2023-02-02 15:39 UTC, mps4dev commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +        if (task == null){
Kontroler nie powinien miec zadnej logiki. To mapper powinien sprawdzac null

2023-02-02 21:55 UTC, JanSikorski commented
Przeniosłem if(null){return null;} wszystkich metod mapujących w mapperze

2023-02-03 15:26 UTC, mps4dev approved these changes

2023-02-04 00:14 UTC, closed without merging